package SMU.BAMBOO.Hompage.mock.repository;

import SMU.BAMBOO.Hompage.domain.enums.KnowledgeType;
import SMU.BAMBOO.Hompage.domain.knowledge.entity.Knowledge;
import SMU.BAMBOO.Hompage.domain.knowledge.repository.KnowledgeRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakeKnowledgeRepository implements KnowledgeRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Knowledge> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Optional<Knowledge> findById(Long id) {
        return data.stream()
                .filter(knowledge -> knowledge.getKnowledgeId().equals(id))
                .findAny();
    }

    @Override
    public Knowledge save(Knowledge knowledge) {
        if (knowledge.getKnowledgeId() == null || knowledge.getKnowledgeId() == 0) {
            Knowledge newKnowledge = Knowledge.builder()
                    .knowledgeId(autoGeneratedId.incrementAndGet())
                    .member(knowledge.getMember())
                    .title(knowledge.getTitle())
                    .content(knowledge.getContent())
                    .type(knowledge.getType())
                    .views(knowledge.getViews())
                    .images(new ArrayList<>(knowledge.getImages()))
                    .files(new ArrayList<>(knowledge.getFiles()))
                    .knowledgeComments(new ArrayList<>(knowledge.getKnowledgeComments()))
                    .build();

            data.add(newKnowledge);
            return newKnowledge;
        } else {
            deleteById(knowledge.getKnowledgeId());
            data.add(knowledge);
            return knowledge;
        }
    }

    @Override
    public void deleteById(Long id) {
        data.removeIf(knowledge -> knowledge.getKnowledgeId().equals(id));
    }

    @Override
    public Page<Knowledge> findAllByType(KnowledgeType type, Pageable pageable) {
        List<Knowledge> filteredList = data.stream()
                .filter(knowledge -> knowledge.getType().equals(type))
                .collect(Collectors.toList());

        return getPagedResult(filteredList, pageable);
    }

    @Override
    public Page<Knowledge> findAllByTitle(String title, Pageable pageable) {
        List<Knowledge> filteredList = data.stream()
                .filter(knowledge -> knowledge.getTitle().toLowerCase().contains(title.toLowerCase()))
                .collect(Collectors.toList());

        return getPagedResult(filteredList, pageable);
    }

    @Override
    public Page<Knowledge> findByTypeAndTitle(KnowledgeType type, String keyword, Pageable pageable) {
        List<Knowledge> filteredList = data.stream()
                .filter(knowledge -> knowledge.getType().equals(type)
                        && knowledge.getTitle().toLowerCase().contains(keyword.toLowerCase()))
                .collect(Collectors.toList());

        return getPagedResult(filteredList, pageable);
    }

    @Override
    public Page<Knowledge> findAll(Pageable pageable) {
        return getPagedResult(data, pageable);
    }

    private Page<Knowledge> getPagedResult(List<Knowledge> knowledgeList, Pageable pageable) {
        int start = (int) pageable.getOffset();
        int end = Math.min(start + pageable.getPageSize(), knowledgeList.size());
        List<Knowledge> pagedKnowledge = knowledgeList.subList(start, end);

        return new PageImpl<>(pagedKnowledge, pageable, knowledgeList.size());
    }
}
