package SMU.BAMBOO.Hompage.mock.repository;

import SMU.BAMBOO.Hompage.domain.libraryPostComment.entity.LibraryPostComment;
import SMU.BAMBOO.Hompage.domain.libraryPostComment.repository.LibraryPostCommentRepository;
import SMU.BAMBOO.Hompage.global.exception.CustomException;
import SMU.BAMBOO.Hompage.global.exception.ErrorCode;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class FakeLibraryPostCommentRepository implements LibraryPostCommentRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<LibraryPostComment> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public LibraryPostComment findByIdOrThrow(Long id) {
        return data.stream()
                .filter(c -> c.getLibraryPostCommentId().equals(id))
                .findFirst()
                .orElseThrow(() -> new CustomException(ErrorCode.LIBRARY_COMMENT_NOT_EXIST));
    }

    @Override
    public LibraryPostComment findParentByIdOrThrow(Long id) {
        return data.stream()
                .filter(c -> c.getLibraryPostCommentId().equals(id))
                .findFirst()
                .orElseThrow(() -> new CustomException(ErrorCode.LIBRARY_PARENT_COMMENT_NOT_EXIST));
    }

    @Override
    public void validateBelongsToPost(LibraryPostComment comment, Long postId) {
        if (!comment.getLibraryPost().getLibraryPostId().equals(postId)) {
            throw new CustomException(ErrorCode.COMMENT_LIBRARY_MISMATCH);
        }
    }

    @Override
    public int countByPostId(Long libraryPostId) {
        return (int) data.stream()
                .filter(c -> c.getLibraryPost().getLibraryPostId().equals(libraryPostId))
                .count();
    }

    @Override
    public void deleteAllByLibraryPostId(Long libraryPostId) {
        data.removeIf(c -> c.getLibraryPost().getLibraryPostId().equals(libraryPostId));
    }
}

