package SMU.BAMBOO.Hompage.mock.repository;

import SMU.BAMBOO.Hompage.domain.knowledgeComment.entity.KnowledgeComment;
import SMU.BAMBOO.Hompage.domain.knowledgeComment.repository.KnowledgeCommentRepository;
import SMU.BAMBOO.Hompage.global.exception.CustomException;
import SMU.BAMBOO.Hompage.global.exception.ErrorCode;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class FakeKnowledgeCommentRepository implements KnowledgeCommentRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<KnowledgeComment> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public KnowledgeComment findByIdOrThrow(Long id) {
        return data.stream()
                .filter(comment -> comment.getKnowledgeCommentId().equals(id))
                .findFirst()
                .orElseThrow(() -> new CustomException(ErrorCode.KNOWLEDGE_COMMENT_NOT_EXIST));
    }

    @Override
    public KnowledgeComment findParentByIdOrThrow(Long id) {
        return data.stream()
                .filter(comment -> comment.getKnowledgeCommentId().equals(id))
                .findFirst()
                .orElseThrow(() -> new CustomException(ErrorCode.KNOWLEDGE_PARENT_COMMENT_NOT_EXIST));
    }

    @Override
    public void validateBelongsToKnowledge(KnowledgeComment comment, Long knowledgeId) {
        if (!comment.getKnowledge().getKnowledgeId().equals(knowledgeId)) {
            throw new CustomException(ErrorCode.COMMENT_KNOWLEDGE_MISMATCH);
        }
    }

    @Override
    public void deleteAllByKnowledgeId(Long knowledgeId) {
        data.removeIf(comment -> comment.getKnowledge().getKnowledgeId().equals(knowledgeId));
    }

}
